### ISSUE TITLE
Criar estrutra obras-ui

### ISSUE THREAD

**Issue by pedro-hos** [transparenciasjc/obras#3]
Criar a estrutura do projeto obras-ui
- Angular
- Gulp
- Bower

**Comment by PauloLuan** [comment]
@pedro-hos use o [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular) e coloque com ES6 :) vai usar o Angular 2 ? queria aprender rs

**Comment by danilovaz** [comment]
estou montando a estrutura ui do projeto utilizando o generator  proposto pelo @PauloLuan porém com Angular 1.x

**Comment by pedro-hos** [comment]
@danilovaz Beleza. Depois temos que definir as telas, os filtros etc

**Comment by danilovaz** [comment]
eu criei o esqueleto do ui em angular e enviei o pull request, se tiver de acordo com o padrão de qualidade esperado só dar merge. se tiver algo que precise ser alterado, me avisem

cc @transparenciasjc/dev

**Comment by pedro-hos** [comment]
@danilovaz vc add as paradas do bower no gitignore?

**Comment by danilovaz** [comment]
@pedro-hos sim, criei. dentro do obras-ui/.gitignore adicionei as seguintes regras:

```
node_modules/
bower_components/
coverage/
.sass-cache/
.idea/
.tmp/
dist/

```
