### ISSUE TITLE
Criar README de como rodar

### ISSUE THREAD

**Issue by pedro-hos** [transparenciasjc/obras#6]

**Comment by danilovaz** [comment]
criar o README de como rodar o front?

**Comment by pedro-hos** [comment]
Isso, para quem for desenvolver. Tipo, vc precisa de rodar npm, bower, etc :smile:

**Comment by danilovaz** [comment]
@pedro-hos legal, vou ver isso. vi que o @IuryAlves já adicionou o Travis, se ele for tocar o README sussa, me foco em terminar de ver a listagem senão mais tarde vejo as duas coisas

**Comment by IuryAlves** [comment]
@danilovaz @pedro-hos posso adicionar as coisas no README

**Comment by danilovaz** [comment]
@IuryAlves feshow!

**Comment by IuryAlves** [comment]
@pedro-hos  @danilovaz  adicionei no readme na #13 

Danilo, dá uma olhada lá e ver se está tudo ok.
