### ISSUE TITLE
Sugestão de versionamento

### ISSUE THREAD

**Issue by danilovaz** [transparenciasjc/obras#7]
Queria sugerir e ver o que vocês acham de fazer um controle de versionamento e utilizar um padrão para isso?

Pensei em algo relacionado com [esse post](http://willianjusten.com.br/semantic-version/) do Willian Justen.

Basicamente gira em torno de `x.y.z` onde:
- x : Major Versions, que seriam as versões principais fechadas.
- y:  Minor Versions, que seriam adições de pequenas melhorias.
- z:  Patchs, que seriam correções de bugs.

resultando em versions nesse estilo `1.0.0` obviamente, seria interessante se tirássemos proveito das releases que o Github já disponibiliza através do uso de tags.

Atualmente no obras-ui ao criar o init do front, eu versionei como `0.1.0` já que se trata ainda de uma Minor Version. O que acham?

Creio que são passos simples e não amarram o desenvolvimento. E acabam contribuindo pra qualidade já que os commits girariam em torno das versions e tags/releases proporcionando um maior entendimento do que é uma feature nova fechada, uma melhoria isolada e correções de bugs.

Fica aí a sugestão, é nozes :chestnut: :+1:

**Comment by pedro-hos** [comment]
Concordo @danilovaz o server seria 1.0.0 então? Certo?

**Comment by IuryAlves** [comment]
@danilovaz Concordo, semantic versioning é bem útil.
@pedro-hos  O projeto só vai pra 1.x.x quando estiver estável.

**Comment by danilovaz** [comment]
@pedro-hos isso mesmo que o @IuryAlves disse, quando o server estiver com a versão estável ele entra como `1.y.z` e toda feature nova (que não impacte na versão estável) incrementa um número em `y` e toda correção de bugs incrementa em `z`. enquanto a versão não é estável, incrementamos as novas features em `y`, exemplo: `0.4.2` (4 features adicionadas e 2 bugs corrigidos).

**Comment by pedro-hos** [comment]
Show de bola, vamos fazer assim
