### ISSUE TITLE
Add paginação para pegar todas obras

### ISSUE THREAD

**Issue by pedro-hos** [transparenciasjc/obras#9]
@jesuino fez isso no transparência :smile: Depois ele vai me ajudar rs

**Comment by jesuino** [comment]
hahaha tem que usar o max results e o first result

https://github.com/transparenciasjc/repasse-server/blob/master/repasse-server/src/main/java/org/jugvale/transfgov/service/impl/TransferenciaService.java#L142-L147

**Comment by pedro-hos** [comment]
@jesuino feito :dancers:
